import os
from datetime import datetime
from functools import wraps

import numpy as np
import pandas as pd
from flask import Flask, request, redirect, url_for, session, flash, render_template_string
from sqlalchemy import create_engine, text
from werkzeug.security import generate_password_hash, check_password_hash
from sklearn.ensemble import IsolationForest

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "change-this-secret-key-before-deployment")

# Render Postgres is used when DATABASE_URL is set; SQLite is the local fallback.
DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///bizbuddy.db")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg://", 1)
elif DATABASE_URL.startswith("postgresql://") and "+psycopg" not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)

engine = create_engine(DATABASE_URL, pool_pre_ping=True, future=True)

def init_db():
    with engine.begin() as conn:
        if DATABASE_URL.startswith("sqlite"):
            conn.execute(text("""CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL, business_name TEXT NOT NULL DEFAULT ''
            )"""))
        else:
            conn.execute(text("""CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(120) UNIQUE NOT NULL,
                password_hash TEXT NOT NULL, business_name TEXT NOT NULL DEFAULT ''
            )"""))
        try:
            conn.execute(text("ALTER TABLE users ADD COLUMN business_name TEXT NOT NULL DEFAULT ''"))
        except Exception:
            pass

        username = os.environ.get("ADMIN_USERNAME", "admin")
        password = os.environ.get("ADMIN_PASSWORD", "BizBuddy@2026")
        exists = conn.execute(text("SELECT id FROM users WHERE username=:u"), {"u": username}).first()
        if not exists:
            conn.execute(text("INSERT INTO users (username,password_hash,business_name) VALUES (:u,:p,:b)"),
                         {"u": username, "p": generate_password_hash(password), "b": "Default Business"})
        row = conn.execute(text("SELECT id FROM users WHERE username=:u"), {"u": username}).first()
        default_bid = row[0] if row else conn.execute(text("SELECT id FROM users ORDER BY id LIMIT 1")).scalar()

        defs = {
            "sales": "date TEXT, product TEXT, quantity DOUBLE PRECISION, price DOUBLE PRECISION",
            "expenses": "date TEXT, category TEXT, amount DOUBLE PRECISION",
            "inventory": "product TEXT, stock DOUBLE PRECISION, reorder_level DOUBLE PRECISION"
        }
        for table, fields in defs.items():
            if DATABASE_URL.startswith("sqlite"):
                fields = fields.replace("DOUBLE PRECISION", "REAL")
                conn.execute(text(f"CREATE TABLE IF NOT EXISTS {table} (id INTEGER PRIMARY KEY AUTOINCREMENT, business_id INTEGER, {fields})"))
            else:
                conn.execute(text(f"CREATE TABLE IF NOT EXISTS {table} (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, business_id INTEGER, {fields})"))
            try:
                conn.execute(text(f"ALTER TABLE {table} ADD COLUMN business_id INTEGER"))
            except Exception:
                pass
            if default_bid is not None:
                conn.execute(text(f"UPDATE {table} SET business_id=:bid WHERE business_id IS NULL"), {"bid": default_bid})

init_db()

BASE_STYLE = """
*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:#f3f6fb;color:#152238}
a{color:inherit;text-decoration:none}.nav{height:58px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 5%;gap:16px}
.brand{font-weight:800;letter-spacing:.2px}.navlinks{display:flex;gap:18px;flex-wrap:wrap;font-size:14px}.navlinks a:hover{color:#9fc5ff}
.wrap{max-width:1120px;margin:28px auto;padding:0 20px}.muted{color:#64748b}.card{background:white;border-radius:16px;padding:22px;box-shadow:0 6px 20px #182b4810;margin-bottom:18px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:15px}.metric{background:#fff;border-radius:16px;padding:19px;box-shadow:0 5px 18px #182b480d}.metric small{display:block;color:#64748b;margin-bottom:8px}.metric strong{font-size:25px}
h1{font-size:29px;margin:0 0 10px}h2{font-size:20px;margin:0 0 17px}p{line-height:1.5}
.btn{display:inline-block;border:0;border-radius:10px;background:#2563eb;color:white;padding:11px 16px;font-weight:700;cursor:pointer}.btn:hover{background:#1d4ed8}.btn.secondary{background:#e8eef8;color:#183153}
input,select{width:100%;padding:12px 13px;border:1px solid #d7deea;border-radius:10px;font:inherit;background:white}label{display:block;font-weight:650;font-size:13px;margin:14px 0 7px}
.formrow{display:grid;grid-template-columns:1fr 1fr;gap:14px}.flash{padding:12px 14px;background:#fff7ed;border-left:4px solid #f59e0b;border-radius:8px;margin-bottom:12px}
.alert{padding:14px 16px;border-left:4px solid #e05252;background:#fff5f5;border-radius:10px;margin:10px 0}.alert.medium{border-color:#f59e0b;background:#fffbeb}
.pill{display:inline-block;padding:4px 9px;border-radius:99px;background:#fee2e2;color:#991b1b;font-size:12px;font-weight:700}
.login-bg{min-height:100vh;background:radial-gradient(circle at 15% 15%,#dbeafe 0,transparent 32%),linear-gradient(135deg,#f8fafc,#eaf0fa);display:grid;grid-template-columns:1.1fr .9fr;align-items:center;padding:5vw;gap:5vw}
.login-copy h1{font-size:clamp(32px,4vw,54px);line-height:1.08;max-width:560px}.login-copy p{font-size:17px;color:#64748b;max-width:480px}
.login-card{max-width:430px;width:100%;justify-self:center;padding:32px;border-radius:22px;background:#fff;box-shadow:0 22px 70px #172b4d1c}
.logo-mark{display:inline-grid;place-items:center;background:#2563eb;color:white;width:43px;height:43px;border-radius:13px;font-size:22px;margin-bottom:18px}
@media(max-width:720px){.login-bg{grid-template-columns:1fr;padding:26px}.login-copy{display:none}.nav{padding:0 16px;height:auto;min-height:58px}.navlinks{gap:10px}.formrow{grid-template-columns:1fr}}
"""

LOGIN = """<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · BizBuddy AI</title><style>""" + BASE_STYLE + """</style></head>
<body><main class="login-bg"><section class="login-copy"><div class="logo-mark">✦</div><p style="font-weight:800;color:#2563eb;letter-spacing:2px;text-transform:uppercase;font-size:12px">BizBuddy AI</p><h1>Make smarter business decisions, every day.</h1><p>Your business data, translated into clear insights, inventory warnings and practical next steps.</p><p>✓ Sales and expense analytics &nbsp; ✓ Stock alerts &nbsp; ✓ Business insights</p></section>
<section class="login-card"><div class="logo-mark">✦</div><h2 style="font-size:26px;margin-bottom:6px">Welcome back</h2><p class="muted" style="margin-top:0">Sign in to your business workspace.</p>
{% with messages=get_flashed_messages() %}{% for message in messages %}<div class="flash">{{message}}</div>{% endfor %}{% endwith %}
<form method="post"><label for="username">Username</label><input id="username" name="username" autocomplete="username" placeholder="Enter your username" required>
<label for="password">Password</label><input id="password" type="password" name="password" autocomplete="current-password" placeholder="Enter your password" required>
<button class="btn" style="width:100%;margin-top:22px" type="submit">Sign in securely →</button></form>
<p style="margin-top:22px">New business? <a style="color:#2563eb;font-weight:700" href="{{url_for('register')}}">Create an account</a></p>
<p class="muted" style="font-size:12px;margin-top:22px">Each business has a separate private workspace.</p></section></main></body></html>"""

REGISTER = """<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Create account · BizBuddy AI</title><style>""" + BASE_STYLE + """</style></head>
<body><main class="login-bg"><section class="login-copy"><div class="logo-mark">✦</div><h1>Your business. Your numbers. Your insights.</h1><p>Create a private workspace. Other accounts cannot see your sales, expenses or inventory.</p></section>
<section class="login-card"><div class="logo-mark">✦</div><h2 style="font-size:26px">Create business account</h2>
{% with messages=get_flashed_messages() %}{% for message in messages %}<div class="flash">{{message}}</div>{% endfor %}{% endwith %}
<form method="post"><label>Business name</label><input name="business_name" placeholder="e.g. Sunrise General Store" required maxlength="120">
<label>Username</label><input name="username" autocomplete="username" placeholder="Choose a username" required maxlength="120">
<label>Password</label><input type="password" name="password" autocomplete="new-password" placeholder="At least 8 characters" minlength="8" required>
<label>Confirm password</label><input type="password" name="confirm_password" autocomplete="new-password" placeholder="Re-enter password" minlength="8" required>
<button class="btn" style="width:100%;margin-top:22px" type="submit">Create my workspace →</button></form>
<p style="margin-top:22px">Already registered? <a style="color:#2563eb;font-weight:700" href="{{url_for('login')}}">Sign in</a></p></section></main></body></html>"""


LAYOUT = """<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{title}} · BizBuddy AI</title><style>""" + BASE_STYLE + """</style></head><body>
<nav class="nav"><a class="brand" href="{{url_for('dashboard')}}">✦ BizBuddy AI</a><div class="navlinks"><span>{{business_name}}</span><a href="{{url_for('dashboard')}}">Dashboard</a><a href="{{url_for('upload')}}">Upload</a><a href="{{url_for('alerts')}}">Alerts</a><a href="{{url_for('mode')}}">Mode</a><a href="{{url_for('logout')}}">Logout</a></div></nav>
<div class="wrap">{% with messages=get_flashed_messages() %}{% for message in messages %}<div class="flash">{{message}}</div>{% endfor %}{% endwith %}{{content|safe}}</div></body></html>"""

def page(title, content, **context):
    return render_template_string(LAYOUT, title=title, content=render_template_string(content, **context), business_name=session.get("business_name", "Business workspace"))

def login_required(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("login"))
        return fn(*args, **kwargs)
    return wrapper

def read_table(table):
    try:
        with engine.connect() as conn:
            return pd.read_sql(text(f"SELECT * FROM {table} WHERE business_id=:bid"), conn, params={"bid": session.get("user_id")})
    except Exception:
        return pd.DataFrame()

def money(value):
    try:
        return "₹{:,.0f}".format(float(value))
    except Exception:
        return "₹0"

def get_analysis():
    sales = read_table("sales")
    expenses = read_table("expenses")
    inventory = read_table("inventory")
    revenue = 0.0
    anomalies = []
    forecast = 0.0
    if not sales.empty:
        for col in ["quantity", "price"]:
            sales[col] = pd.to_numeric(sales.get(col), errors="coerce").fillna(0)
        sales["total"] = sales["quantity"] * sales["price"]
        revenue = float(sales["total"].sum())
        if "date" in sales.columns:
            daily = sales.groupby("date", dropna=True)["total"].sum().sort_index()
            if len(daily) >= 2:
                forecast = max(0.0, float(daily.tail(min(7, len(daily))).mean()))
            if len(sales) >= 5:
                try:
                    features = sales[["quantity", "price", "total"]].replace([np.inf, -np.inf], np.nan).fillna(0)
                    model = IsolationForest(contamination="auto", random_state=42)
                    flags = model.fit_predict(features)
                    anomalies = sales.loc[flags == -1].to_dict("records")
                except Exception:
                    anomalies = []
    expense_total = 0.0
    if not expenses.empty and "amount" in expenses.columns:
        expenses["amount"] = pd.to_numeric(expenses["amount"], errors="coerce").fillna(0)
        expense_total = float(expenses["amount"].sum())
    low_stock = []
    if not inventory.empty and {"stock", "reorder_level"}.issubset(inventory.columns):
        inventory["stock"] = pd.to_numeric(inventory["stock"], errors="coerce").fillna(0)
        inventory["reorder_level"] = pd.to_numeric(inventory["reorder_level"], errors="coerce").fillna(0)
        low_stock = inventory[inventory["stock"] <= inventory["reorder_level"]].to_dict("records")
    recommendations = []
    if low_stock:
        recommendations.append(f"Replenish {len(low_stock)} low-stock product(s) before they affect sales.")
    if anomalies:
        recommendations.append("Investigate unusual sales activity and related dates/products.")
    if expense_total > revenue:
        recommendations.append("Review major expenses because expenses exceed revenue.")
    if not recommendations:
        recommendations.append("Keep tracking sales, expenses and stock to surface useful business patterns.")
    return {"sales": sales, "expenses": expenses, "inventory": inventory, "revenue": revenue,
            "expense_total": expense_total, "profit": revenue-expense_total, "forecast": forecast,
            "low_stock": low_stock, "anomalies": anomalies, "recommendations": recommendations}

@app.route("/", methods=["GET", "POST"])
def login():
    if "user_id" in session:
        return redirect(url_for("dashboard"))
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        with engine.connect() as conn:
            user = conn.execute(text("SELECT id, username, password_hash, business_name FROM users WHERE username=:u"), {"u": username}).mappings().first()
        if user and check_password_hash(user["password_hash"], password):
            session.clear()
            session["user_id"] = user["id"]
            session["username"] = user["username"]
            session["business_name"] = user["business_name"] or user["username"]
            session["mode"] = "Professional"
            return redirect(url_for("dashboard"))
        flash("The username or password is incorrect. Please try again.")
    return render_template_string(LOGIN)


@app.route("/register", methods=["GET", "POST"])
def register():
    if "user_id" in session:
        return redirect(url_for("dashboard"))
    if request.method == "POST":
        business_name = request.form.get("business_name", "").strip()
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")
        if not business_name or not username or not password:
            flash("Please complete every field.")
        elif len(password) < 8:
            flash("Use a password with at least 8 characters.")
        elif password != confirm:
            flash("The passwords do not match.")
        else:
            try:
                with engine.begin() as conn:
                    conn.execute(text("INSERT INTO users (username,password_hash,business_name) VALUES (:u,:p,:b)"),
                                 {"u":username, "p":generate_password_hash(password), "b":business_name})
                    user = conn.execute(text("SELECT id,username,business_name FROM users WHERE username=:u"),
                                        {"u":username}).mappings().first()
                session.clear()
                session["user_id"] = user["id"]
                session["username"] = user["username"]
                session["business_name"] = user["business_name"]
                session["mode"] = "Professional"
                flash("Your private business workspace is ready.")
                return redirect(url_for("dashboard"))
            except Exception:
                flash("That username may already be taken. Choose another one.")
    return render_template_string(REGISTER)

@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))

@app.route("/dashboard")
@login_required
def dashboard():
    a = get_analysis()
    mode = session.get("mode", "Professional")
    metrics = f"""
    <h1>{session.get("business_name", "Business")} Dashboard</h1><p class="muted">{mode} Mode — Your private business workspace</p>
    <div class="grid">
      <div class="metric"><small>Revenue</small><strong>{money(a['revenue'])}</strong></div>
      <div class="metric"><small>Expenses</small><strong>{money(a['expense_total'])}</strong></div>
      <div class="metric"><small>Profit</small><strong>{money(a['profit'])}</strong></div>
      <div class="metric"><small>Next-period sales estimate</small><strong>{money(a['forecast'])}</strong></div>
      <div class="metric"><small>Low Stock</small><strong>{len(a['low_stock'])}</strong></div>
      <div class="metric"><small>Anomalies</small><strong>{len(a['anomalies'])}</strong></div>
    </div>
    <section class="card" style="margin-top:20px"><h2>🤖 Autonomous AI Agent</h2>
    {''.join('<p>💡 <b>Recommendation:</b> '+r+'</p>' for r in a['recommendations'])}</section>
    <section class="card"><h2>🚨 Proactive Alerts</h2>
    {''.join('<div class="alert"><b>Low Inventory Detected</b><p>'+str(len(a['low_stock']))+' product(s) are at or below reorder level.</p><b>Action:</b> Review inventory and place a restocking order. <span class="pill">HIGH</span></div>' for _ in ([1] if a['low_stock'] else []))}
    {''.join('<div class="alert"><b>Sales Anomaly Detected</b><p>'+str(len(a['anomalies']))+' unusual sales record(s) detected.</p><b>Action:</b> Check the dates, products and quantities to confirm whether these are genuine.</div>' for _ in ([1] if a['anomalies'] else []))}
    {''.join('<div class="alert medium"><b>Expenses exceed revenue</b><p>Current recorded expenses are higher than recorded revenue.</p><b>Action:</b> Review costs and verify the selected reporting period.</div>' for _ in ([1] if a['expense_total'] > a['revenue'] else []))}
    {('<p class="muted">No alerts currently detected.</p>' if not a['low_stock'] and not a['anomalies'] and a['expense_total'] <= a['revenue'] else '')}
    </section>"""
    return page("Dashboard", metrics)

@app.route("/upload", methods=["GET", "POST"])
@login_required
def upload():
    if request.method == "POST":
        kind = request.form.get("kind", "")
        file = request.files.get("file")
        schemas = {"sales": ["date", "product", "quantity", "price"],
                   "expenses": ["date", "category", "amount"],
                   "inventory": ["product", "stock", "reorder_level"]}
        if kind not in schemas or not file or not file.filename.lower().endswith(".csv"):
            flash("Choose a data type and a valid CSV file.")
            return redirect(url_for("upload"))
        try:
            df = pd.read_csv(file)
            df.columns = [str(c).strip().lower() for c in df.columns]
            missing = [c for c in schemas[kind] if c not in df.columns]
            if missing:
                flash("CSV is missing required columns: " + ", ".join(missing))
                return redirect(url_for("upload"))
            df = df[schemas[kind]].copy()
            for col in df.columns:
                if col in ("quantity", "price", "amount", "stock", "reorder_level"):
                    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
                else:
                    df[col] = df[col].fillna("").astype(str)
            # Replace each uploaded dataset atomically; uploaded records are now stored in the database.
            with engine.begin() as conn:
                conn.execute(text(f"DELETE FROM {kind} WHERE business_id=:bid"), {"bid": session.get("user_id")})
                for _, row in df.iterrows():
                    cols = list(df.columns) + ["business_id"]
                    values = {c: (None if pd.isna(row[c]) else row[c].item() if hasattr(row[c], "item") else row[c]) for c in df.columns}
                    values["business_id"] = session.get("user_id")
                    names = ", ".join(cols)
                    binds = ", ".join(":" + c for c in cols)
                    conn.execute(text(f"INSERT INTO {kind} ({names}) VALUES ({binds})"), values)
            flash(f"Uploaded {len(df)} records to your {kind} workspace.")
            return redirect(url_for("dashboard"))
        except Exception as exc:
            flash("Upload failed. Check the CSV format and try again.")
    content = """
    <h1>Upload Business Data</h1><p class="muted">Upload one CSV at a time. Files are stored only in your business workspace; each upload replaces only your own dataset of that type.</p>
    <section class="card"><form method="post" enctype="multipart/form-data">
    <label>Dataset type</label><select name="kind" required><option value="sales">Sales</option><option value="expenses">Expenses</option><option value="inventory">Inventory</option></select>
    <label>CSV file</label><input type="file" name="file" accept=".csv" required>
    <p class="muted" style="font-size:13px">Sales: date, product, quantity, price<br>Expenses: date, category, amount<br>Inventory: product, stock, reorder_level</p>
    <button class="btn" type="submit">Upload and analyse</button></form></section>"""
    return page("Upload", content)

@app.route("/alerts")
@login_required
def alerts():
    a = get_analysis()
    items = []
    if a["low_stock"]:
        items.append(f"<div class='alert'><b>Low Inventory Detected</b><p>{len(a['low_stock'])} product(s) at or below reorder level.</p></div>")
    if a["anomalies"]:
        items.append(f"<div class='alert'><b>Sales Anomaly Detected</b><p>{len(a['anomalies'])} unusual record(s) found.</p></div>")
    if a["expense_total"] > a["revenue"]:
        items.append("<div class='alert medium'><b>Expense Warning</b><p>Expenses currently exceed revenue.</p></div>")
    content = "<h1>Proactive Alerts</h1>" + ("".join(items) if items else "<section class='card'>No alerts detected from the currently uploaded data.</section>")
    return page("Alerts", content)

@app.route("/mode", methods=["GET", "POST"])
@login_required
def mode():
    if request.method == "POST":
        session["mode"] = request.form.get("mode", "Professional")
        flash("Dashboard mode updated.")
        return redirect(url_for("dashboard"))
    current = session.get("mode", "Professional")
    content = f"""
    <h1>Choose Your Workspace Mode</h1><section class="card"><form method="post">
    <label>Dashboard mode</label><select name="mode">
    <option {'selected' if current == 'Professional' else ''}>Professional</option>
    <option {'selected' if current == 'Simple' else ''}>Simple</option>
    </select><p class="muted">Professional mode presents business metrics. Simple mode is intended for plain-language guidance.</p>
    <button class="btn" type="submit">Save mode</button></form></section>"""
    return page("Mode", content)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)), debug=False)
